### ISSUE TITLE
Not able to install the plugin

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [elastic/template-kibana-plugin#10]
While installing the plugin using (sao kibana-plugin) facing error  

plugin-helpers postinstall

'plugin-helpers' is not recognized as an internal or external command,
operable program or batch file.

Is environment issue?

**Comment by w33ble** [comment]
`plugin-helpers` is another package that the template uses. You can see the repo [right here](https://github.com/elastic/kibana-plugin-helpers).

Sounds like perhaps the module install didn't happen. You can try running `yarn install` or `npm install`, whichever you are using, from the root of your plugin.

If that doesn't work, it would be helpful to know what OS you're using, and what version.

**Comment by PrabakarKaruppasamy** [comment]
npm install doesn't work. 
_Node Js Version:- 6.11.1
OS:- Windows 10 Pro
Folder Structure Kibana:- E:/ELK4/TestKibana/Plugin_Dev/kibana/kibana
Folder Structure Plugin:-  E:/ELK4/TestKibana/Plugin_Dev/kibana/whowe_

**Comment by w33ble** [comment]
> npm install doesn't work.

What happens? Do you get an error or anything when you try to run it? Can you paste the output here?

**Comment by PrabakarKaruppasamy** [comment]
The error message is given below

_ce-views@0.0.0 postinstall E:\ELK4\TestKibana\Plugin_Dev\kibana\whowe
plugin-helpers postinstall

'plugin-helpers' is not recognized as an internal or external command,
operable program or batch file.

npm WARN ce-views@0.0.0 No repository field.
npm WARN ce-views@0.0.0 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ce-views@0.0.0 postinstall: `plugin-helpers postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ce-views@0.0.0 postinstall script 'plugin-helpers postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ce-views package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     plugin-helpers postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ce-views
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ce-views
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\ELK4\TestKibana\Plugin_Dev\kibana\whowe\npm-debug.log_

**Comment by w33ble** [comment]
Hrm, strange. I'm not sure what's going on here. I had one of the other Windows devs here try it out and it worked fine for them. 

Maybe you're in the wrong path? Looks like you're running this from `E:\ELK4\TestKibana\Plugin_Dev\kibana\whowe`... can you tell me what's in that path? Also, can you share what's in your `package.json` file?

Also, do you have a node_modules path there? And is there anything in it? In particular I'd like to know if there's an `@elastic` path in there. I'm thinking maybe you're installing modules in `--production` mode for some reason, in which case none of the tooling would be installed.

**Comment by w33ble** [comment]
Closing due to lack of response.
