### ISSUE TITLE
generate ReactJS based plugin

### ISSUE THREAD

**Issue by blacktop** [elastic/template-kibana-plugin#13]
I know that the UI is moving towards React components, so it would be awesome to get a reactJS version of a base plugin to start playing with? 😁

**Comment by blacktop** [comment]
or one that uses https://github.com/elastic/eui ?

**Comment by w33ble** [comment]
@elastic/kibana-platform if we were going to add this, do we have a canonical way to bootstrap React apps?

**Comment by kjbekkelund** [comment]
@w33ble Hm, I don't think we have that yet. We've of course got the plugins using it, but no canonical setup as far as I know. I haven't really done React/UI work lately, so I'm not fully up-to-date on how we handle things right now. I know there's some details around the router and things like that too (cc @bmcconaghy, who worked on that).

Would be great to have a template with React + router setup + EUI.

cc @cjcenizal

**Comment by bmcconaghy** [comment]
Yeah I think we are at the point to build something like that.  Do we already supply a base plugin template?  @w33ble @kjbekkelund

**Comment by kjbekkelund** [comment]
@bmcconaghy Yep, check the `template` folder (https://github.com/elastic/template-kibana-plugin/tree/master/template) for the current template

**Comment by w33ble** [comment]
> Do we already supply a base plugin template?

@bmcconaghy you mean... this repo? 😝

**Comment by bmcconaghy** [comment]
Can someone put in a PR to make the name more obvious :-)

**Comment by cjcenizal** [comment]
> Would be great to have a template with React + router setup + EUI

I've added this to the [EUIfication roadmap](https://github.com/elastic/dev/issues/909). This will be a priority for the current release lifecycle (6.3).

**Comment by blacktop** [comment]
![me](https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif)

**Comment by bmcconaghy** [comment]
I'm actually working some on it.

**Comment by w33ble** [comment]
The effort for this is happening upstream in `kbn-plugin-generator`. It's stalled, see https://github.com/elastic/kibana/pull/16937, but either way, the effort should happen upstream. Drop a comment on that PR, or maybe even open an issue in the Kibana repo about it.

**Comment by zallan114** [comment]
I adaped one from kbn-plugin-generator to fit kibana 6.0.2 with latest React/Dom/React-Route, looks good. it's really better than angular one.

**Comment by zallan114** [comment]
but the issue is why the compiled plugin bundle.js is so big, it's almost 10M.......

**Comment by w33ble** [comment]
> why the compiled plugin bundle.js is so big, it's almost 10M.......

It includes a lot of stuff. Both react and angular, a bunch of addons for both, and a boatload of other dependencies. As you can see in the repo, [the dependency list is not small](https://github.com/elastic/kibana/blob/master/package.json#L80).

**Comment by satishwaghela** [comment]
I created sample react visualisation plugin to play : https://github.com/satishwaghela/kibana-react-visualisation-example
