### ISSUE TITLE
Unable to run with default template with particular plugin naming

### ISSUE THREAD

**Issue by ppadovani** [elastic/template-kibana-plugin#14]
Can you please update your documentation to indicate that plugin names cannot:

- have capital letters
- have _

This caused me much frustration.

**Comment by w33ble** [comment]
The template will convert whatever name you give it to the correct format. I'm happy to update or add to any documentation you're talking about though.

We don't have a lot of documentation, other than what's in the template here. Where would you like to see this mentioned?

**Comment by ppadovani** [comment]
It didn't for my first three attempts, not sure why. Perhaps not enough coffee?

Just something in the README. For example right above this HINT:

> HINT: If you need to use a version other than the latest, you can specify it when you run the template

You could just add something like: NOTE: The plugin name, not repository name, must contain all lowercase letters, no dots or underscores.

**Comment by w33ble** [comment]
> It didn't for my first three attempts, not sure why. Perhaps not enough coffee?

Let us know what names didn't work, that sounds like a bug.

In the meantime, I'll get a note about the name into the README.

**Comment by w33ble** [comment]
Closing for lack of response. We can re-open if needed.
