### ISSUE TITLE
Error: unable to find usable node.js executable

### ISSUE THREAD

**Issue by DarkSiderOC** [elastic/template-kibana-plugin#17]
Env:

- node: 6.12.2
- npm: 3.10.10
![kerror](https://user-images.githubusercontent.com/5739391/35870861-0580a9f0-0b63-11e8-8a27-3f64fd678098.PNG)

My kibana and plugin directories are siblings.
`$ ls:
kibana/  stabHavana/
`
Kibana and ES run correctly. I only have this problem when I try to run Kibana with my plugin included.
Kibana is forked for the repository so I'm currently working with the latest relase (7.0.0-alpha1). My plugin was generated running `sao kibana plugin` without any params and I generated everything except for hack and transation files.

Hope this is useful!

**Comment by w33ble** [comment]
The way plugin development is done changed recently in master, and the template hasn't yet been updated to accommodate.

If you're on a the latest Kibana master, you'll need to put your plugin in a `kibana-extra` path, which lives next to `kibana`. You'll then need to upgrade the version of `@elastic/kibana-plugin-helpers` you are using. You'll probably also need to change the eslint setup, and link to the version in `kibana` instead, and use the `kbn` tool to install everything. You plugin's package.json will include:

```
"@elastic/eslint-config-kibana": "link:../../kibana/packages/eslint-config-kibana",
"@elastic/eslint-import-resolver-kibana": "2.0.0",
"@elastic/plugin-helpers": "^9.0.2",
```

Check out the [contributing docs](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#contributing-code) for information on setting things up.

I'll leave this open though, as a reminder to upgrade the template.

**Comment by w33ble** [comment]
Closing this issue since the generator was forked into the Kibana repo, and works with the new dev setup. See https://github.com/elastic/kibana/tree/master/packages/kbn-plugin-generator.
