### ISSUE TITLE
link to @kbn/plugin-helpers when targeting 6.3+

### ISSUE THREAD

**Issue by spalger** [elastic/template-kibana-plugin#18]
Once https://github.com/elastic/kibana/pull/16565 is merged the template will need to link to the `@kbn/plugin-helpers` package from the Kibana repo rather than installing it from NPM. I'm assuming we can do that just for packages targeting 6.3 or greater, which I think means we'll need to cut a new 7.x release for 6.3+ and a new 8.x release for 7.0+

**Comment by w33ble** [comment]
@spalger do we still need this? Aren't we using `kbn-plugin-generator` in 6.3+?

**Comment by spalger** [comment]
Yeah, this is taken care of by `kbn-plugin-generator`
