### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by PlatonovDmitriy** [elastic/template-kibana-plugin#2]
Hi guys.
Your idea is very well, but I found bug. 
When I try to generate plugin via command `sao template-kibana-plugin` I catched error
`npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/template-template-kibana-plugin `
But when I change command to `sao kibana-plugin` , generator work fine.

**Comment by w33ble** [comment]
Whoops, you're right, that's a typo. I'll get that fixed, thanks!
