### ISSUE TITLE
template-kibana-plugin 404 not found 

### ISSUE THREAD

**Issue by evannalikeyou** [elastic/template-kibana-plugin#23]
When I try to generate plugin via command sao template-kibana-plugin I catched error
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/template-template-kibana-plugin

**Comment by spalger** [comment]
There are two `template-` bits in that url, so you probably ran `sao template-kibana-plugin` instead of `sao kibana-plugin`.

Also, please use the plugin generator in the Kibana repo if you’re targeting 
Kibana 6.3+ https://github.com/elastic/kibana/tree/master/packages/kbn-plugin-generator
