### ISSUE TITLE
Start kibana with under development plugin

### ISSUE THREAD

**Issue by deyb** [elastic/template-kibana-plugin#3]
The documentation says "Start Kibana in development mode with your new plugin included". How do you start kibana with the new plugin since it is still under development ? What command do I need to run ?

By default, it does not include the new plugin. I am running `npm start` in the new plugin directory which is the sibling directory of `kibana`. When I try running kibana, it complains that the new plugin module cannot be found.

ERROR in ./optimize/bundles/kibana.entry.js
    Module not found: Error: Cannot resolve module 'plugins/kb-newplugin/kb-newplugin'

**Comment by deyb** [comment]
It fails when you try to export the module through `visTypes` since the plugin is not in the `kibana/plugins`.

**Comment by w33ble** [comment]
When you run npm start, it actually [uses the plugin-helpers module](https://github.com/elastic/template-kibana-plugin/blob/master/template/package.json#L12) to start it, which will set the kibana pluginsPath property to include your plugin's root path. This is how we do plugins development at Elastic.

> Cannot resolve module 'plugins/kb-newplugin/kb-newplugin'

This path seems suspicious. Can you share a listing of the files in your plugin? If you're on Linux/Mac, you can run `tree -L 2` from the root of your plugin, that should provide enough information.

Also, in the top-level `index.js`, can you share what you have for the `uiExports` configuration?

**Comment by w33ble** [comment]
Closing for lack of feedback
